language: java
jdk: openjdk8
install: skip

before_install:
  - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - GRADLE_OPTS="-Xms128m -Xmx2g"

script:
  - ./gradlew build --scan -s

deploy:
  provider: script
  cleanup: false
  script:
    - ./gradlew bintrayPublish -Dorg.gradle.project.bintray.user=$BINTRAY_USER -Dorg.gradle.project.bintray.key=$BINTRAY_KEY
  # TODO add in publishing for plugin
  #    - ./ -Dorg.gradle.project.gradle.publish.key=$PLUGIN_PORTAL_API_KEY -Dorg.gradle.project.gradle.publish.secret=$PLUGIN_PORTAL_API_SECRET
  on:
    tags: true
    branch: master
  name: $project_version
