site:
  about:
    siteName: mcspring
    siteDescription: Add Spring to any plugin
Editorial:
  social:
    github: 'kylepls/mcspring'
  legacySearch: false
  metaComponents:
    - type: 'orchidSearch'
  menu:
    - type: 'separator'
      title: 'Wiki'
    - type: 'wiki'
    - type: 'page'
      itemId: 'Changelog'
    - type: 'separator'
      title: 'API Docs'
    - type: 'kotlindocClasses'
      moduleType: 'kotlindocClasses'
      node: 'classes'
      asSubmenu: true
      submenuTitle: 'Classes'
    - type: 'kotlindocPackages'
      moduleType: 'kotlindoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'Packages'

kotlindoc:
  sourceDirs:
    - './../../../mcspring-api/mcspring-base/src/main/kotlin'
    - './../../../mcspring-api/mcspring-subcommands/src/main/kotlin'
    - './../../../mcspring-api/mcspring-vault/src/main/kotlin'
        #  modules:
#    - name: 'mcspring-base'
#      moduleGroup: 'group-one'
#      sourceDirs:
#        - './../../../../mcspring-api/mcspring-base/src/main/kotlin'
#    - name: 'mcspring-subcommands'
#      sourceDirs:
#        - './../../../../../mcspring-api/mcspring-subcommands/src/main/kotlin'
#  sourcePages:
#    menu:
#      - type: 'sourcedocPageLinks'
#        moduleType: 'kotlindoc'
#        itemTitleType: 'SIGNATURE'
#        includeItems: true
